project_name: hevy

builds:
  - main: ./main.go
    binary: hevy
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
